<a href="https://colab.research.google.com/github/uditrajmr3/tensorflow/blob/main/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Fundamentals of Tensor

In [ ]:
# import Tensorflowa
import tensorflow as tf
print(tf.__version__)

2.15.0


### Create tensors with tf.constant()

In [ ]:
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
# check the number of dimensions of a tensor (ndim stands for number of dimensions)
scalar.ndim

0

In [ ]:
# Create a vector
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
# check the dimension of vector
vector.ndim

1

In [ ]:
# Create a matrix (has more dimensions)
matrix = tf.constant([[10, 7], [10, 10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [10, 10]], dtype=int32)>

In [ ]:
matrix.ndim

2

In [ ]:
# Create another matrix
another_matrix = tf.constant([[10., 7.], [3., 2.], [8., 9.]],  dtype=tf.float16) # specify datatype with dtype parameter
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [ ]:
# No of dimensions of another matrix
another_matrix.ndim

2

In [ ]:
# Let's create a tensor
tensor = tf.constant([[[1,2,3], [4,5,6]], [[7,8,9], [10,11,12]], [[13,14,15], [16,17,18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [ ]:
tensor.ndim

3

### What we 've leart so far?

###* Scalar: a single number
### * Vector: a number with direction (e.g. wind speed and direction)
### * Matrix: a 2-dimensional array of numbers
### * Tensor: an n-dimensional array of numbers (where n can be any number, a 0-dimnsional tensor is a scalar,  a 1-dimensional tensor is a vector)

### Creating tensors with `tf.variable`

In [ ]:
# Create the same tensors as above with `tf.Variable()`
changable_tensor = tf.Variable([10, 7])
unchangable_tensor = tf.constant([10, 7])
changable_tensor, unchangable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [ ]:
# reassigning a tensor value
changable_tensor[0].assign(7)
changable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

### Creating random tensors

 Random tensors are tensors of some arbitary size which contain random numbers


In [ ]:
# Create 2 random (but same) tensors
random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.normal(shape=(3, 2))
random_1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193765, -1.8107855 ]], dtype=float32)>

### Shuffle the order of elements in a tensor

In [ ]:
# Shuffle a tensor (valuable for when you want to shuffle the data so the inherent order doesn't effect learning
not_shuffled  = tf.constant([[10, 7], [3, 4], [2, 1]])
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  1]], dtype=int32)>

In [ ]:
not_shuffled.ndim

2

In [ ]:
# let's shuffle the non shuffled tensor 😁
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [ 2,  1],
       [10,  7]], dtype=int32)>

In [ ]:
# let's shuffle it again 😎
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [10,  7],
       [ 2,  1]], dtype=int32)>

In [ ]:
# let's shuffle it again but with a global and operational level seed 😜
tf.random.set_seed(26) # global level random seed
tf.random.shuffle(not_shuffled, seed=26) # operational level random seed

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  1],
       [ 3,  4],
       [10,  7]], dtype=int32)>

### Other ways to make tensors

In [ ]:
# Create a tensors of all Ones (1s)
tf.ones([10, 8])

<tf.Tensor: shape=(10, 8), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [ ]:
# Now, Let's try to create a tensor full of zeros 😁
tf.zeros(shape=[5,7])

<tf.Tensor: shape=(5, 7), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

### How to turn Numpy arrays  into tensors

The difference between Numpy & Tensorflow tensors is that tesnsors can be run on a GPU (much faster for numerical computing).


In [ ]:
import numpy as np
numpy_A = np.arange(1, 25, dtype=np.int32) # Create a numpy array between 1 & 25
numpy_A

# X = tf.constant(some_matrix) # capital for matrix or tensor
# y = tf.constant(vector) # non-capital for vector

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [ ]:
A  = tf.constant(numpy_A, shape=(2, 3, 4))
A

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int32)>

In [ ]:
A.ndim

3

## Getting Information From Tensors

* Shape : The length (no of elements) of each of the dimension of tensor
* Rank : The number of tensor dimensions. A scalar has a rank 0, vector has 1, matrix has 2 and tensor has n
* Axis or dimension : A particular dimension of a tensor
* Size : The total no of items in the tensor

In [ ]:
# shape
A.shape

TensorShape([2, 3, 4])

In [ ]:
# rank
A.ndim

3

In [ ]:
# Axis or dimension
A[:, 1]

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[ 5,  6,  7,  8],
       [17, 18, 19, 20]], dtype=int32)>

In [ ]:
# Size
tf.size(A)

<tf.Tensor: shape=(), dtype=int32, numpy=24>

In [ ]:
# Let's try to  create a rank 4 tensor
rank_4_tensor = tf.zeros(shape=(2, 3, 4, 5))
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
# shape, rank, axis, size
rank_4_tensor.shape, rank_4_tensor.ndim, rank_4_tensor[0], tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]),
 4,
 <tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
 array([[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],
 
        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],
 
        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]], dtype=float32)>,
 <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [ ]:
# Get Various attributes of a tensor
print("Datetype of every element: ", rank_4_tensor.dtype)
print("Number of dimensions (rank): ", rank_4_tensor.ndim)
print("Shape of tensor: ", rank_4_tensor.shape)
print("Elements along the 0 axis: ", rank_4_tensor.shape[0])
print("Elements along the last axis:", rank_4_tensor.shape[-1])
print("Total number of elements in our tensor", tf.size(rank_4_tensor))
print("Total number of elements in our tensor", tf.size(rank_4_tensor).numpy())

Datetype of every element:  <dtype: 'float32'>
Number of dimensions (rank):  4
Shape of tensor:  (2, 3, 4, 5)
Elements along the 0 axis:  2
Elements along the last axis: 5
Total number of elements in our tensor tf.Tensor(120, shape=(), dtype=int32)
Total number of elements in our tensor 120


### Indexing tensors

Tensors caan be indexed just like Python lists.

In [ ]:
array_A = [1,2,3,4,5]
array_A[:2]

[1, 2]

In [ ]:
# Get the first 2 elements of each dimension
rank_4_tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [ ]:
# Get the first element from each dimension from each index except for the final one
rank_4_tensor[:1,:1,:1,:]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
# Create a rank 2 tensor
rank_2_tensor = tf.constant([[2,6], [5,3]])
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 6],
       [5, 3]], dtype=int32)>

In [ ]:
# Get the last element of each of row of rank 2 tensor
rank_2_tensor[:, -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([6, 3], dtype=int32)>

In [ ]:
# Add in extra dimentsion to rank 2 tensor
rank_3_tensor = rank_2_tensor[..., tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[2],
        [6]],

       [[5],
        [3]]], dtype=int32)>

In [ ]:
# Alternative to tf.newaxis
tf.expand_dims(rank_2_tensor, axis=-1) #"-1" mmeans expand the final axis

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[2],
        [6]],

       [[5],
        [3]]], dtype=int32)>

In [ ]:
# Expand the middle axis
tf.expand_dims(rank_2_tensor, axis=1) #"1" mmeans expand the middle or second axis

<tf.Tensor: shape=(2, 1, 2), dtype=int32, numpy=
array([[[2, 6]],

       [[5, 3]]], dtype=int32)>

In [ ]:
# Expand the first axis
tf.expand_dims(rank_2_tensor, axis=0) #"0" mmeans expand the first axis

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[2, 6],
        [5, 3]]], dtype=int32)>

### Manipulating tensors (tensor operations)

**Basic operations**

`+`, `-`, `*`, `/`

In [ ]:
# You can add values to a tensor using the addition operator
tensor = tf.constant([[2,6],[5,3]])
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[12, 16],
       [15, 13]], dtype=int32)>

In [ ]:
# Original tensor remians unchanged even after the operation
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 6],
       [5, 3]], dtype=int32)>

In [ ]:
# But that can be changed using assignment operator
tensor
tensor = tensor + 10
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[12, 16],
       [15, 13]], dtype=int32)>

In [ ]:
# Using Subtraction operator on tensor
tensor - 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 6],
       [5, 3]], dtype=int32)>

In [ ]:
# Using multiplication opoerator on tensor
tensor * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[120, 160],
       [150, 130]], dtype=int32)>

In [ ]:
# Operations can be done using built-in functions too
tf.multiply(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[120, 160],
       [150, 130]], dtype=int32)>

###**Matrix Multiplication **

In machine learning, matrix multiplication is one of the most common tensor operations.

In [ ]:
print(tensor)
tf.matmul(tensor, tensor)

tf.Tensor(
[[12 16]
 [15 13]], shape=(2, 2), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[384, 400],
       [375, 409]], dtype=int32)>

In [ ]:
tensor * tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[144, 256],
       [225, 169]], dtype=int32)>

In [ ]:
tensor_A = tf.constant([[1,2,5],[7,2,1],[3,3,3]])
tensor_B = tf.constant([[3,5],[6,7],[1,8]])
print(tensor * tensor)
tf.matmul(tensor_A, tensor_B)

tf.Tensor(
[[144 256]
 [225 169]], shape=(2, 2), dtype=int32)


<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]], dtype=int32)>

In [ ]:
# matrix multiplication with Python operator `@`
tensor_A @ tensor_B

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]], dtype=int32)>

In [ ]:
# Transpose vs Reshape
tensor_B, tf.transpose(tensor_B), tf.reshape(tensor_B, shape=(2,3))

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[3, 5],
        [6, 7],
        [1, 8]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[3, 6, 1],
        [5, 7, 8]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[3, 5, 6],
        [7, 1, 8]], dtype=int32)>)

**The Dot Product**

Matrix Multiplication is also reffered to as the dot product.

You can perform matrix multiplication using:
* `tf.manual()`
* `tf.tensordot()`

In [ ]:
# Perform the dot product on A and B (requires X or Y to be transposed)
print(tensor_A)
print(tensor_B)

tf.tensordot(tf.transpose(tensor_A), tensor_B, axes=1)

tf.Tensor(
[[1 2 5]
 [7 2 1]
 [3 3 3]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[3 5]
 [6 7]
 [1 8]], shape=(3, 2), dtype=int32)


<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[48, 78],
       [21, 48],
       [24, 56]], dtype=int32)>

In [ ]:
# Perform the dot product on A and B (requires X or Y to be reshapred)
tensor_A = tf.constant([[1,5],[4,7],[2,9]])
print(tensor_A)
print(tensor_B)

tf.matmul(tensor_A, tf.reshape(tensor_B, shape=(2, 3)))

tf.Tensor(
[[1 5]
 [4 7]
 [2 9]], shape=(3, 2), dtype=int32)
tf.Tensor(
[[3 5]
 [6 7]
 [1 8]], shape=(3, 2), dtype=int32)


<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[38, 10, 46],
       [61, 27, 80],
       [69, 19, 84]], dtype=int32)>

Genarally, when performing  matrix multiplication on 2 tensors and one of the axes doesn't line up, you will transpose (rather than reshape) one of the tensors to satisfy the matrix multiplication rules.

### Changing datatype of a tensor

In [ ]:
tf.__version__

'2.15.0'

In [ ]:
# Create a new tensor with deafault datatype (float32)
B = tf.constant([3.2, 2.6])
B.dtype

tf.float32

In [ ]:
C = tf.constant([26, 53])
C.dtype

tf.int32

In [ ]:
# Change from float32 to float16 (reduced precision)
D = tf.cast(B, dtype=tf.float16)
D, D.dtype

(<tf.Tensor: shape=(2,), dtype=float16, numpy=array([3.2, 2.6], dtype=float16)>,
 tf.float16)

In [ ]:
# Change dtype from int32 to float32
E = tf.cast(C, dtype=tf.float32)
E, E.dtype

(<tf.Tensor: shape=(2,), dtype=float32, numpy=array([26., 53.], dtype=float32)>,
 tf.float32)

### Aggregating Tensors

Aggregating tensors = condensing them from multiple values down to a smaller amount of values

In [ ]:
# Get the absolute values
F = tf.constant([-12, -13])
F

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([-12, -13], dtype=int32)>

In [ ]:
tf.abs(F)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([12, 13], dtype=int32)>

Let's go through the following types of aggregations:

* Get the minimum
* Get the maximum
* Get the mean of a tensor
* Get the sum of a tensor

In [ ]:
# Create a random tensor with values between 0 and 100 of size 50
G = tf.constant(np.random.randint(0, 100, size=50))
G

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([26, 50, 91, 91, 33, 36, 74, 18, 30,  1, 51, 15, 64,  6, 86,  3, 91,
       51,  9, 66,  7, 88, 22, 99, 45, 95, 45, 97, 17, 49, 71, 93, 90, 19,
       98, 21, 39, 48, 57, 33, 69, 45, 85, 39, 23, 72, 39, 26, 15, 83])>

In [ ]:
tf.size(G), G.shape, G.ndim

(<tf.Tensor: shape=(), dtype=int32, numpy=50>, TensorShape([50]), 1)

In [ ]:
# Find the minimum
tf.reduce_min(G)

<tf.Tensor: shape=(), dtype=int64, numpy=1>

In [ ]:
# Find the maximum
tf.reduce_max(G)

<tf.Tensor: shape=(), dtype=int64, numpy=99>

In [ ]:
# FInd the mean of tensor
tf.reduce_mean(G)

<tf.Tensor: shape=(), dtype=int64, numpy=50>

In [ ]:
# Find the sum of tensor
tf.reduce_sum(G)

<tf.Tensor: shape=(), dtype=int64, numpy=2521>

In [ ]:
# Find the variance of tensor
import tensorflow_probability as tfp
tfp.stats.variance(G), tf.math.reduce_variance(tf.cast(G, dtype=tf.float32))

(<tf.Tensor: shape=(), dtype=int64, numpy=911>,
 <tf.Tensor: shape=(), dtype=float32, numpy=911.28357>)

In [ ]:
# Find the standard deviation
tf.math.reduce_std(tf.cast(G, dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=30.187473>

## Find the positional maximum and minimum

In [ ]:
# Create a new tensor for finding positional minimum and maximum

tf.random.set_seed(26)
H = tf.random.uniform(shape=[50])
H

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.35321426, 0.8510207 , 0.73598063, 0.02492225, 0.28126347,
       0.11404037, 0.57268095, 0.16411662, 0.4924934 , 0.46897972,
       0.3936354 , 0.71776795, 0.8297758 , 0.5223682 , 0.68932474,
       0.5470909 , 0.45918477, 0.02133095, 0.12147582, 0.9045199 ,
       0.22628713, 0.52647173, 0.6587366 , 0.1342969 , 0.7278055 ,
       0.79442835, 0.31169748, 0.45529938, 0.54803276, 0.3399105 ,
       0.03035474, 0.41112888, 0.91096187, 0.28609097, 0.2686572 ,
       0.6433593 , 0.7034298 , 0.46730375, 0.88040304, 0.90248466,
       0.56153655, 0.7327405 , 0.44688606, 0.7967427 , 0.20459628,
       0.749146  , 0.924708  , 0.6938491 , 0.9530442 , 0.4455942 ],
      dtype=float32)>

In [ ]:
# Find the positional maximum
tf.argmax(H)

<tf.Tensor: shape=(), dtype=int64, numpy=48>

In [ ]:
# index on largest value position
H[tf.argmax(H)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9530442>

In [ ]:
# Finc the max of H
tf.reduce_max(H)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9530442>

In [ ]:
# Check for equality
assert H[tf.argmax(H)] == tf.reduce_max(H)

In [ ]:
# Find the positional minimum
tf.argmin(H)

<tf.Tensor: shape=(), dtype=int64, numpy=17>

In [ ]:
# index on smallest value position
H[tf.argmin(H)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.021330953>

In [ ]:
# Finc the min of H
tf.reduce_min(H)

<tf.Tensor: shape=(), dtype=float32, numpy=0.021330953>

In [ ]:
# Check for equality
assert H[tf.argmin(H)] == tf.reduce_min(H)

###Squeezing the tensor

In [ ]:
# Create a tensor
tf.random.set_seed(26)
I = tf.constant(tf.random.uniform(shape=[50]), shape=(1,1,1,1,50))
I

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.35321426, 0.8510207 , 0.73598063, 0.02492225, 0.28126347,
           0.11404037, 0.57268095, 0.16411662, 0.4924934 , 0.46897972,
           0.3936354 , 0.71776795, 0.8297758 , 0.5223682 , 0.68932474,
           0.5470909 , 0.45918477, 0.02133095, 0.12147582, 0.9045199 ,
           0.22628713, 0.52647173, 0.6587366 , 0.1342969 , 0.7278055 ,
           0.79442835, 0.31169748, 0.45529938, 0.54803276, 0.3399105 ,
           0.03035474, 0.41112888, 0.91096187, 0.28609097, 0.2686572 ,
           0.6433593 , 0.7034298 , 0.46730375, 0.88040304, 0.90248466,
           0.56153655, 0.7327405 , 0.44688606, 0.7967427 , 0.20459628,
           0.749146  , 0.924708  , 0.6938491 , 0.9530442 , 0.4455942 ]]]]],
      dtype=float32)>

In [ ]:
I.shape

TensorShape([1, 1, 1, 1, 50])

In [ ]:
I_squeezed = tf.squeeze(I)
I_squeezed

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.35321426, 0.8510207 , 0.73598063, 0.02492225, 0.28126347,
       0.11404037, 0.57268095, 0.16411662, 0.4924934 , 0.46897972,
       0.3936354 , 0.71776795, 0.8297758 , 0.5223682 , 0.68932474,
       0.5470909 , 0.45918477, 0.02133095, 0.12147582, 0.9045199 ,
       0.22628713, 0.52647173, 0.6587366 , 0.1342969 , 0.7278055 ,
       0.79442835, 0.31169748, 0.45529938, 0.54803276, 0.3399105 ,
       0.03035474, 0.41112888, 0.91096187, 0.28609097, 0.2686572 ,
       0.6433593 , 0.7034298 , 0.46730375, 0.88040304, 0.90248466,
       0.56153655, 0.7327405 , 0.44688606, 0.7967427 , 0.20459628,
       0.749146  , 0.924708  , 0.6938491 , 0.9530442 , 0.4455942 ],
      dtype=float32)>

### One-hot encoding tensors

In [ ]:
# Create a list of indices
some_list = [3, 1, 0, 2, 4]

# One hot encode the list
tf.one_hot(some_list, 5)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1.]], dtype=float32)>

In [ ]:
# Specify custom values for one hot encoding
tf.one_hot(some_list, 5, on_value="True", off_value="False")

<tf.Tensor: shape=(5, 5), dtype=string, numpy=
array([[b'False', b'False', b'False', b'True', b'False'],
       [b'False', b'True', b'False', b'False', b'False'],
       [b'True', b'False', b'False', b'False', b'False'],
       [b'False', b'False', b'True', b'False', b'False'],
       [b'False', b'False', b'False', b'False', b'True']], dtype=object)>

### Squaring, log, square root

In [ ]:
# Create a new tensor
J = tf.range(1, 10)
J

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [ ]:
# Square it
tf.square(J)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [ ]:
# Find the square root
tf.cast(J, dtype=tf.float32), tf.sqrt(tf.cast(J, dtype=tf.float32))

(<tf.Tensor: shape=(9,), dtype=float32, numpy=array([1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float32)>,
 <tf.Tensor: shape=(9,), dtype=float32, numpy=
 array([1.       , 1.4142135, 1.7320508, 2.       , 2.2360678, 2.4494896,
        2.6457512, 2.828427 , 3.       ], dtype=float32)>)

In [ ]:
# Find the log
tf.math.log(tf.cast(J, dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

### Tensors and NumPy

In [ ]:
# Create a tensor directly from a numpy array
K = tf.constant(np.array([2., 6., 5., 3.]))
K

<tf.Tensor: shape=(4,), dtype=float64, numpy=array([2., 6., 5., 3.])>

In [ ]:
# Convert tensor back to numpy array
np.array(K), type(np.array(K))

(array([2., 6., 5., 3.]), numpy.ndarray)

In [ ]:
# Convert tensor back to numpy array
K.numpy(), type(K.numpy())

(array([2., 6., 5., 3.]), numpy.ndarray)

In [ ]:
K_numpy = tf.constant([2., 6., 5., 3.])
K.dtype, K_numpy.dtype

(tf.float64, tf.float32)

### Finding access to GPUs

In [ ]:
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [ ]:
!nvidia-smi

Sat Jul 13 07:41:16 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   54C    P0              29W /  70W |    107MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--